<?php
namespace October\Rain\Config\Tests;

use Config;

class ConfigTest extends TestCase
{
    protected string $configPath = __DIR__.'/fixtures/config';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createApplication();
    }


    public function test_a_config_file(): void
    {
        Config::Write('config-file.test_a', 'this is change test_a.');
        $configFile = $this->getConfig();
        $this->assertArrayHasKey('test_a', $configFile);
        $this->assertArrayHasKey('test_two', $configFile);
        $this->assertArrayHasKey('test_array_one', $configFile);

        $this->assertSame('this is change test_a.', $configFile['test_a']);
    }

    public function test_two_config_file(): void
    {
        Config::Write('config-file.test_two', 121);
        $configFile = $this->getConfig();

        $this->assertArrayHasKey('test_a', $configFile);
        $this->assertArrayHasKey('test_two', $configFile);
        $this->assertArrayHasKey('test_array_one', $configFile);

        $this->assertSame(121, $configFile['test_two']);
    }

    public function test_array_config_file(): void
    {
        Config::Write('config-file.test_array_one.index_1', 'string index instead int');
        Config::Write('config-file.test_array_one.index_2', 222);
        Config::Write('config-file.test_array_one.index_3', 'string index instead array');
        Config::Write('config-file.test_array_one.index_4', [1]);
        Config::Write('config-file.test_array_one.index_5', 111);
        $value = [
            'index_1' => 'string index instead int',
            'index_2' => 222,
            'index_3' => 'string index instead array',
            'index_4' => [1],
            'index_5' => 111
        ];

        $configFile = $this->getConfig();

        $this->assertArrayHasKey('test_a', $configFile);
        $this->assertArrayHasKey('test_array_one', $configFile);
        $this->assertArrayHasKey('test_two', $configFile);
        $this->assertSame($value, $configFile['test_array_one']);
    }

    public function getConfig(){
        return include $this->configPath . '/config-file.php';
    }
}